# version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3-python3.8
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    AIRFLOW__WEBSERVER__SECRET_KEY: "secret_key"
    PYTHONPATH: "/opt/airflow"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/scripts:/opt/airflow/scripts
    - ./airflow/data:/opt/airflow/data
    - ./airflow/sql:/opt/airflow/sql
    - ./airflow/requirements.txt:/requirements.txt

services:
  airflow-db:
    image: postgres:16-alpine
    container_name: airflow-db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  warehouse-db:
    image: postgres:16-alpine
    container_name: warehouse-db
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d property_db"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      airflow-db:
        condition: service_healthy
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && airflow webserver"

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && airflow scheduler"

volumes:
  airflow_db_data:
  warehouse_db_data: